import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Mail, MessageSquare, Smartphone, Instagram, Send, ShieldCheck } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

const defaults:any={email:{apiKey:'',fromEmail:'',fromName:'Hotel Operations'},sms:{accountSid:'',authToken:'',from:''},whatsapp:{accountSid:'',authToken:'',from:'',contentSid:''},instagram:{accessToken:'',instagramUserId:'',verifyToken:'',graphVersion:'v23.0',autoReplyEnabled:false,autoReplyMessage:'Merhaba! Mesajınız alındı. Ekibimiz en kısa sürede dönüş yapacaktır.'}};

export default function Integrations({hotelId}:{hotelId?:number}){
 const {toast}=useToast(); const [channel,setChannel]=useState('email'); const [forms,setForms]=useState<any>(defaults); const [enabled,setEnabled]=useState<any>({email:false,sms:false,whatsapp:false,instagram:false}); const [testTo,setTestTo]=useState(''); const [testMessage,setTestMessage]=useState('Hotel Operations test mesajı');
 const {data=[]}=useQuery<any[]>({queryKey:['/api/integrations',hotelId],queryFn:async()=>{const r=await fetch(`/api/integrations?hotelId=${hotelId}`);return r.json();},enabled:!!hotelId});
 useEffect(()=>{const next:any={...defaults};const en:any={...enabled};for(const x of data){next[x.channel]={...next[x.channel],...(x.settings||{})};en[x.channel]=x.enabled;}setForms(next);setEnabled(en);},[data]);
 const save=async()=>{await apiRequest('PUT',`/api/integrations/${channel}`,{hotelId,enabled:enabled[channel],settings:forms[channel]});toast({title:'Entegrasyon kaydedildi',description:`${channel} ayarları güncellendi.`});};
 const test=async()=>{try{const r=await apiRequest('POST','/api/integrations/test',{hotelId,channel,to:testTo,message:testMessage});const x=await r.json();toast({title:x.ok?'Test başarılı':'Test gönderilemedi',description:x.reason||'Mesaj sonucu kaydedildi.',variant:x.ok?'default':'destructive'});}catch(e:any){toast({title:'Test hatası',description:e.message,variant:'destructive'});}};
 const f=forms[channel]||{}; const set=(k:string,v:any)=>setForms((p:any)=>({...p,[channel]:{...p[channel], [k]:v}}));
 return <div className="p-6 space-y-6">
  <Card><CardContent className="p-4 flex gap-3 items-start"><ShieldCheck className="h-5 w-5 text-green-600 mt-0.5"/><div><div className="font-semibold">Teslim edilebilirlik ve spam koruması</div><div className="text-sm text-muted-foreground">SMS/WhatsApp/Instagram otomasyonları yalnızca açık opt-in bulunan alıcılara gönderilir; suppression kayıtları engellenir. WhatsApp işletme başlatmalı mesajlarda onaylı şablon kullanılması gerekir. E-posta için doğrulanmış gönderici alan adı ve SPF/DKIM kurulumu önerilir.</div></div></CardContent></Card>
  <Tabs value={channel} onValueChange={setChannel}>
   <TabsList className="grid grid-cols-5 w-full"><TabsTrigger value="email"><Mail className="h-4 w-4 mr-2"/>E-posta</TabsTrigger><TabsTrigger value="sms"><Smartphone className="h-4 w-4 mr-2"/>SMS</TabsTrigger><TabsTrigger value="whatsapp"><MessageSquare className="h-4 w-4 mr-2"/>WhatsApp</TabsTrigger><TabsTrigger value="instagram"><Instagram className="h-4 w-4 mr-2"/>Instagram DM</TabsTrigger><TabsTrigger value="telegram"><Send className="h-4 w-4 mr-2"/>Telegram</TabsTrigger></TabsList>
   <TabsContent value="email"><IntegrationCard title="SendGrid / Transactional Email" enabled={enabled.email} setEnabled={(v:any)=>setEnabled((p:any)=>({...p,email:v}))} onSave={save}><Field label="SendGrid API Key" value={f.apiKey||''} onChange={v=>set('apiKey',v)} type="password"/><Field label="Doğrulanmış From E-mail" value={f.fromEmail||''} onChange={v=>set('fromEmail',v)}/><Field label="Gönderen adı" value={f.fromName||''} onChange={v=>set('fromName',v)}/></IntegrationCard></TabsContent>
   <TabsContent value="sms"><IntegrationCard title="Twilio SMS" enabled={enabled.sms} setEnabled={(v:any)=>setEnabled((p:any)=>({...p,sms:v}))} onSave={save}><Field label="Account SID" value={f.accountSid||''} onChange={v=>set('accountSid',v)}/><Field label="Auth Token" value={f.authToken||''} onChange={v=>set('authToken',v)} type="password"/><Field label="From Number" value={f.from||''} onChange={v=>set('from',v)}/></IntegrationCard></TabsContent>
   <TabsContent value="whatsapp"><IntegrationCard title="Twilio WhatsApp Business" enabled={enabled.whatsapp} setEnabled={(v:any)=>setEnabled((p:any)=>({...p,whatsapp:v}))} onSave={save}><Field label="Account SID" value={f.accountSid||''} onChange={v=>set('accountSid',v)}/><Field label="Auth Token" value={f.authToken||''} onChange={v=>set('authToken',v)} type="password"/><Field label="WhatsApp Sender (+E.164)" value={f.from||''} onChange={v=>set('from',v)}/><Field label="Approved Content SID (önerilir)" value={f.contentSid||''} onChange={v=>set('contentSid',v)}/><p className="text-xs text-muted-foreground">WhatsApp business-initiated mesajlarda onaylı template ve opt-in gerekir.</p></IntegrationCard></TabsContent>
   <TabsContent value="instagram"><IntegrationCard title="Meta Instagram Messaging" enabled={enabled.instagram} setEnabled={(v:any)=>setEnabled((p:any)=>({...p,instagram:v}))} onSave={save}><Field label="Access Token" value={f.accessToken||''} onChange={v=>set('accessToken',v)} type="password"/><Field label="Instagram Professional Account ID" value={f.instagramUserId||''} onChange={v=>set('instagramUserId',v)}/><Field label="Webhook Verify Token" value={f.verifyToken||''} onChange={v=>set('verifyToken',v)} type="password"/><Field label="Graph API Version" value={f.graphVersion||'v23.0'} onChange={v=>set('graphVersion',v)}/><div className="flex items-center justify-between border rounded p-3"><div><Label>Otomatik DM yanıtı</Label><p className="text-xs text-muted-foreground">Gelen DM'lere tanımlı mesajla cevap verir.</p></div><Switch checked={!!f.autoReplyEnabled} onCheckedChange={v=>set('autoReplyEnabled',v)}/></div><Field label="Otomatik yanıt" value={f.autoReplyMessage||''} onChange={v=>set('autoReplyMessage',v)}/></IntegrationCard></TabsContent>
   <TabsContent value="telegram"><Card><CardHeader><CardTitle>Telegram Bot</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm">Mevcut Telegram görev workflow'un korunmuştur. Bot tokenı Render Environment Variables üzerinden yönetilir. Personel eşleştirme, görev atama, işleme alma ve tamamlama mevcut sistem üzerinden devam eder.</p><p className="text-xs text-muted-foreground">TELEGRAM_BOT_TOKEN ve TELEGRAM_BOT_USERNAME değerlerini Render'da tutmaya devam edin.</p></CardContent></Card></TabsContent>
  </Tabs>
  {channel!=='telegram' && <Card><CardHeader><CardTitle>Test Gönderimi</CardTitle></CardHeader><CardContent className="grid md:grid-cols-3 gap-3 items-end"><div><Label>Alıcı</Label><Input value={testTo} onChange={e=>setTestTo(e.target.value)} placeholder="E-posta / +905... / Instagram ID"/></div><div><Label>Mesaj</Label><Input value={testMessage} onChange={e=>setTestMessage(e.target.value)}/></div><div className="flex gap-2"><Button onClick={save}>Ayarları Kaydet</Button><Button variant="outline" onClick={test}><Send className="h-4 w-4 mr-2"/>Test</Button></div></CardContent></Card>}
 </div>
}
function IntegrationCard({title,enabled,setEnabled,onSave,children}:{title:string,enabled:boolean,setEnabled:(v:boolean)=>void,onSave:()=>void,children:any}){return <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{title}</CardTitle><div className="flex items-center gap-2"><Label>Aktif</Label><Switch checked={enabled} onCheckedChange={setEnabled}/></div></CardHeader><CardContent className="space-y-4">{children}<Button onClick={onSave}>Ayarları Kaydet</Button></CardContent></Card>}
function Field({label,value,onChange,type='text'}:{label:string,value:string,onChange:(v:string)=>void,type?:string}){return <div><Label>{label}</Label><Input type={type} value={value} onChange={e=>onChange(e.target.value)}/></div>}
