import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Tabs,TabsContent,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Package, ArrowDownToLine, ArrowUpFromLine, ChefHat, ClipboardList } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
export default function InventoryCenter({hotelId,userRole}:{hotelId?:number,userRole?:string}){
 const {toast}=useToast();const [tab,setTab]=useState('stock');const [sku,setSku]=useState('');const [name,setName]=useState('');const [unit,setUnit]=useState('adet');const [category,setCategory]=useState('');const [minStock,setMinStock]=useState('0');const [parStock,setParStock]=useState('0');const [cost,setCost]=useState('0');const [storeId,setStoreId]=useState('');const [itemId,setItemId]=useState('');const [qty,setQty]=useState('1');const [moveType,setMoveType]=useState('receipt');const [reqType,setReqType]=useState('issue');const [reqItems,setReqItems]=useState<any[]>([]);const [notes,setNotes]=useState('');const [recipeName,setRecipeName]=useState('');const [recipeCategory,setRecipeCategory]=useState('');const [recipePrice,setRecipePrice]=useState('0');const [recipeYield,setRecipeYield]=useState('1');const [recipeItems,setRecipeItems]=useState<any[]>([]);
 const q=useQuery<any[]>({queryKey:['/api/inventory/stock',hotelId],queryFn:async()=>{const r=await fetch(`/api/inventory/stock?hotelId=${hotelId}`);return r.json();},enabled:!!hotelId});const items=q.data||[];const {data:stores=[]}=useQuery<any[]>({queryKey:['/api/inventory/stores',hotelId],queryFn:async()=>{const r=await fetch(`/api/inventory/stores?hotelId=${hotelId}`);return r.json();},enabled:!!hotelId});const {data:transactions=[]}=useQuery<any[]>({queryKey:['/api/inventory/transactions',hotelId],queryFn:async()=>{const r=await fetch(`/api/inventory/transactions?hotelId=${hotelId}`);return r.json();},enabled:!!hotelId});const {data:requests=[]}=useQuery<any[]>({queryKey:['/api/inventory/requests',hotelId],queryFn:async()=>{const r=await fetch(`/api/inventory/requests?hotelId=${hotelId}`);return r.json();},enabled:!!hotelId});const {data:recipes=[]}=useQuery<any[]>({queryKey:['/api/recipes',hotelId],queryFn:async()=>{const r=await fetch(`/api/recipes?hotelId=${hotelId}`);return r.json();},enabled:!!hotelId});
 const refresh=()=>{q.refetch();};
 const addItem=async()=>{try{await apiRequest('POST','/api/inventory/items',{hotelId,sku,name,category,unit,minStock:Number(minStock),parStock:Number(parStock),cost:Number(cost)});toast({title:'Malzeme eklendi'});setSku('');setName('');refresh();}catch(e:any){toast({title:'Hata',description:e.message,variant:'destructive'});}};
 const movement=async()=>{try{await apiRequest('POST','/api/inventory/transactions',{hotelId,storeId:Number(storeId),itemId:Number(itemId),quantity:Number(qty),type:moveType});toast({title:'Stok hareketi kaydedildi'});refresh();}catch(e:any){toast({title:'Hata',description:e.message,variant:'destructive'});}};
 const request=async()=>{try{await apiRequest('POST','/api/inventory/requests',{hotelId,type:reqType,notes,items:reqItems});toast({title:'Stok talebi oluşturuldu',description:'Satınalma/Depo Telegram bildirimleri tetiklendi.'});setReqItems([]);setNotes('');}catch(e:any){toast({title:'Hata',description:e.message,variant:'destructive'});}};
 const saveRecipe=async()=>{try{await apiRequest('POST','/api/recipes',{hotelId,name:recipeName,category:recipeCategory,sellingPrice:Number(recipePrice),yieldQty:Number(recipeYield),items:recipeItems});toast({title:'Reçete kaydedildi'});setRecipeName('');setRecipeItems([]);}catch(e:any){toast({title:'Hata',description:e.message,variant:'destructive'});}};
 return <div className="p-6 space-y-6"><div className="grid grid-cols-2 lg:grid-cols-5 gap-4"><Metric title="Malzeme" value={items.length}/><Metric title="Kritik Stok" value={items.filter((x:any)=>Number(x.stock)<Number(x.min_stock)).length}/><Metric title="Toplam Stok Değeri" value={items.reduce((s:number,x:any)=>s+Number(x.stock)*Number(x.cost),0).toFixed(2)}/><Metric title="Hareket" value={transactions.length}/><Metric title="Reçete" value={recipes.length}/></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="stock"><Package className="h-4 w-4 mr-2"/>Stok</TabsTrigger><TabsTrigger value="movement"><ArrowUpFromLine className="h-4 w-4 mr-2"/>Giriş / Çıkış</TabsTrigger><TabsTrigger value="requests"><ClipboardList className="h-4 w-4 mr-2"/>Talepler</TabsTrigger><TabsTrigger value="recipes"><ChefHat className="h-4 w-4 mr-2"/>Reçeteler</TabsTrigger></TabsList>
 <TabsContent value="stock" className="space-y-4"><Card><CardHeader><CardTitle>Malzeme Kartları</CardTitle></CardHeader><CardContent className="grid md:grid-cols-4 gap-3"><Field label="SKU" value={sku} set={setSku}/><Field label="Malzeme" value={name} set={setName}/><Field label="Kategori" value={category} set={setCategory}/><Field label="Birim" value={unit} set={setUnit}/><Field label="Min. Stok" value={minStock} set={setMinStock}/><Field label="Par" value={parStock} set={setParStock}/><Field label="Birim Maliyet" value={cost} set={setCost}/><div className="flex items-end"><Button onClick={addItem}>Malzeme Ekle</Button></div></CardContent></Card><Card><CardContent className="p-0"><table className="min-w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-left">SKU</th><th className="p-3 text-left">Malzeme</th><th className="p-3 text-left">Kategori</th><th className="p-3 text-left">Birim</th><th className="p-3 text-right">Stok</th><th className="p-3 text-right">Min.</th><th className="p-3 text-right">Maliyet</th></tr></thead><tbody>{items.map((x:any)=><tr key={x.id} className="border-b"><td className="p-3">{x.sku}</td><td className="p-3 font-medium">{x.name}</td><td className="p-3">{x.category||'-'}</td><td className="p-3">{x.unit}</td><td className={`p-3 text-right font-semibold ${Number(x.stock)<Number(x.min_stock)?'text-red-600':''}`}>{Number(x.stock).toFixed(3)}</td><td className="p-3 text-right">{x.min_stock}</td><td className="p-3 text-right">{x.cost}</td></tr>)}</tbody></table></CardContent></Card></TabsContent>
 <TabsContent value="movement"><Card><CardHeader><CardTitle>Stok Giriş / Çıkış</CardTitle></CardHeader><CardContent className="grid md:grid-cols-4 gap-3"><div><Label>Depo</Label><Select value={storeId} onValueChange={setStoreId}><SelectTrigger><SelectValue placeholder="Depo seç"/></SelectTrigger><SelectContent>{stores.map((s:any)=><SelectItem key={s.id} value={String(s.id)}>{s.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Malzeme</Label><Select value={itemId} onValueChange={setItemId}><SelectTrigger><SelectValue placeholder="Malzeme"/></SelectTrigger><SelectContent>{items.map((x:any)=><SelectItem key={x.id} value={String(x.id)}>{x.sku} - {x.name}</SelectItem>)}</SelectContent></Select></div><div><Label>İşlem</Label><Select value={moveType} onValueChange={setMoveType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['receipt','issue','transfer_in','transfer_out','waste','adjustment'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><Field label="Miktar" value={qty} set={setQty}/><div><Button onClick={movement}>Hareket Kaydet</Button></div></CardContent></Card><Card><CardHeader><CardTitle>Son Hareketler</CardTitle></CardHeader><CardContent><div className="space-y-2">{transactions.slice(0,100).map((x:any)=><div key={x.id} className="flex justify-between border-b py-2 text-sm"><span>{x.name} · {x.type}</span><span className={Number(x.quantity)<0?'text-red-600':'text-green-600'}>{Number(x.quantity)>0?'+':''}{x.quantity}</span></div>)}</div></CardContent></Card></TabsContent>
 <TabsContent value="requests" className="space-y-4"><Card><CardHeader><CardTitle>Satınalma / Depo Çıkış Talebi</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid md:grid-cols-3 gap-3"><div><Label>Talep tipi</Label><Select value={reqType} onValueChange={setReqType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="issue">Depodan Çıkış</SelectItem><SelectItem value="purchase">Satınalma</SelectItem></SelectContent></Select></div><Field label="Not" value={notes} set={setNotes}/></div><div className="grid md:grid-cols-4 gap-2"><Select value={itemId} onValueChange={setItemId}><SelectTrigger><SelectValue placeholder="Malzeme"/></SelectTrigger><SelectContent>{items.map((x:any)=><SelectItem key={x.id} value={String(x.id)}>{x.name}</SelectItem>)}</SelectContent></Select><Input placeholder="Miktar" value={qty} onChange={e=>setQty(e.target.value)}/><Button variant="outline" onClick={()=>{const x=items.find((i:any)=>String(i.id)===itemId);if(x)setReqItems(v=>[...v,{itemId:x.id,name:x.name,quantity:Number(qty),unit:x.unit}])}}>Listeye ekle</Button><Button onClick={request}>Talep Gönder</Button></div><div className="space-y-2">{reqItems.map((x:any,i:number)=><div key={i} className="border rounded p-2">{x.name} — {x.quantity} {x.unit}</div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Talepler</CardTitle></CardHeader><CardContent><div className="space-y-2">{requests.map((r:any)=><div key={r.id} className="border rounded p-3 flex justify-between items-center"><div><b>{r.request_no}</b> · {r.type} · {r.department||'-'}<div className="text-xs text-muted-foreground">{r.items?.map((x:any)=>`${x.name} × ${x.quantity}`).join(' · ')}</div></div><div className="flex items-center gap-2"><span>{r.status}</span>{r.status==='pending'&&<Button size="sm" variant="outline" onClick={async()=>{await apiRequest('PATCH',`/api/inventory/requests/${r.id}/status`,{hotelId,status:'approved'});toast({title:'Talep onaylandı'});}}>Onayla</Button>}{r.status==='approved'&&r.type==='issue'&&<Button size="sm" onClick={async()=>{await apiRequest('PATCH',`/api/inventory/requests/${r.id}/status`,{hotelId,status:'fulfilled',storeId:stores[0]?.id});toast({title:'Depo çıkışı tamamlandı'});refresh();}}>Çıkışı Yap</Button>}</div></div>)}</div></CardContent></Card></TabsContent>
 <TabsContent value="recipes" className="space-y-4"><Card><CardHeader><CardTitle>F&B Reçete Kartı</CardTitle></CardHeader><CardContent className="grid md:grid-cols-4 gap-3"><Field label="Menü / Ürün" value={recipeName} set={setRecipeName}/><Field label="Kategori" value={recipeCategory} set={setRecipeCategory}/><Field label="Satış Fiyatı" value={recipePrice} set={setRecipePrice}/><Field label="Yield" value={recipeYield} set={setRecipeYield}/><div className="md:col-span-4 grid md:grid-cols-4 gap-2"><Select value={itemId} onValueChange={setItemId}><SelectTrigger><SelectValue placeholder="Hammadde"/></SelectTrigger><SelectContent>{items.map((x:any)=><SelectItem key={x.id} value={String(x.id)}>{x.name}</SelectItem>)}</SelectContent></Select><Input placeholder="Miktar" value={qty} onChange={e=>setQty(e.target.value)}/><Button variant="outline" onClick={()=>{const x=items.find((i:any)=>String(i.id)===itemId);if(x)setRecipeItems(v=>[...v,{itemId:x.id,name:x.name,quantity:Number(qty),unit:x.unit}])}}>Hammadde Ekle</Button><Button onClick={saveRecipe}>Reçeteyi Kaydet</Button></div><div className="md:col-span-4 space-y-1">{recipeItems.map((x:any,i:number)=><div key={i} className="text-sm border-b py-1">{x.name} — {x.quantity} {x.unit}</div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Reçete Listesi</CardTitle></CardHeader><CardContent><div className="space-y-2">{recipes.map((r:any)=><div key={r.id} className="border rounded p-3 flex items-center justify-between"><div><b>{r.name}</b><div className="text-xs text-muted-foreground">{r.category||'F&B'} · {r.items?.length||0} hammadde</div></div><Button variant="outline" onClick={async()=>{await apiRequest('POST',`/api/recipes/${r.id}/consume`,{hotelId,yieldQty:1});toast({title:'Reçete tüketimi işlendi',description:'İlgili hammaddeler stoktan düşüldü.'});refresh();}}>1 Adet Tüket</Button></div>)}</div></CardContent></Card></TabsContent>
 </Tabs></div>
}
function Field({label,value,set}:{label:string,value:string,set:(v:string)=>void}){return <div><Label>{label}</Label><Input value={value} onChange={e=>set(e.target.value)}/></div>}
function Metric({title,value}:{title:string,value:any}){return <Card><CardContent className="p-4"><div className="text-xs text-muted-foreground">{title}</div><div className="text-2xl font-bold mt-1">{value}</div></CardContent></Card>}
