import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Star, TrendingUp, MessageCircle, Target } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
export default function ReviewTracker({hotelId}:{hotelId?:number}){
 const {toast}=useToast();const [score,setScore]=useState('10');const [source,setSource]=useState('manual');const [guestName,setGuestName]=useState('');const [comment,setComment]=useState('');const {data:stats}=useQuery<any>({queryKey:['/api/reviews/stats',hotelId],queryFn:async()=>{const r=await fetch(`/api/reviews/stats?hotelId=${hotelId}`);return r.json();},enabled:!!hotelId});const {data:reviews=[]}=useQuery<any[]>({queryKey:['/api/reviews',hotelId],queryFn:async()=>{const r=await fetch(`/api/reviews?hotelId=${hotelId}`);return r.json();},enabled:!!hotelId});
 const add=async()=>{try{await apiRequest('POST','/api/reviews',{hotelId,source,guestName,score:Number(score),comment});toast({title:'Review eklendi'});setGuestName('');setComment('');}catch(e:any){toast({title:'Hata',description:e.message,variant:'destructive'});}};
 return <div className="p-6 space-y-6"><div className="grid grid-cols-2 lg:grid-cols-6 gap-4"><Metric icon={<Star/>} title="Review" value={stats?.total??0}/><Metric icon={<Star/>} title="Avg Score" value={stats?.avgScore??0}/><Metric icon={<Target/>} title="NPS" value={stats?.nps??0}/><Metric icon={<TrendingUp/>} title="Performance" value={`%${stats?.performanceScore??0}`}/><Metric icon={<MessageCircle/>} title="Response" value={`%${stats?.responseRate??0}`}/><Metric icon={<Target/>} title="Promoter" value={stats?.promoters??0}/></div>
 <div className="grid lg:grid-cols-3 gap-6"><Card className="lg:col-span-2"><CardHeader><CardTitle>Kaynak Performansı</CardTitle></CardHeader><CardContent><div className="space-y-3">{(stats?.bySource||[]).map((x:any)=><div key={x.source} className="flex items-center gap-4"><div className="w-32 font-medium">{x.source}</div><div className="flex-1 h-3 bg-gray-100 rounded overflow-hidden"><div className="h-full bg-primary" style={{width:`${Math.min(100,Number(x.avg_score)*10)}%`}}/></div><div className="w-20 text-right">{x.avg_score} / {x.total}</div></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Trend / NPS Dağılımı</CardTitle></CardHeader><CardContent><div className="grid grid-cols-3 gap-3 text-center"><div className="border rounded p-3"><div className="text-xs text-muted-foreground">Promoter</div><div className="text-xl font-bold text-green-600">{stats?.promoters??0}</div></div><div className="border rounded p-3"><div className="text-xs text-muted-foreground">Passive</div><div className="text-xl font-bold text-amber-600">{stats?.passives??0}</div></div><div className="border rounded p-3"><div className="text-xs text-muted-foreground">Detractor</div><div className="text-xl font-bold text-red-600">{stats?.detractors??0}</div></div></div><div className="mt-4 space-y-2">{(stats?.monthly||[]).map((m:any)=><div key={m.month} className="flex justify-between text-sm border-b py-1"><span>{m.month}</span><span>{m.total} review · {m.avg_score}</span></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Review Ekle</CardTitle></CardHeader><CardContent className="space-y-3"><div><Label>Kanal</Label><Select value={source} onValueChange={setSource}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['manual','Google','Booking.com','Expedia','Tripadvisor','World of Hyatt','Other'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Skor (0-10)</Label><Input type="number" min="0" max="10" value={score} onChange={e=>setScore(e.target.value)}/></div><div><Label>Misafir</Label><Input value={guestName} onChange={e=>setGuestName(e.target.value)}/></div><div><Label>Yorum</Label><Input value={comment} onChange={e=>setComment(e.target.value)}/></div><Button onClick={add}>Review Kaydet</Button></CardContent></Card></div>
 <Card><CardHeader><CardTitle>Son Reviews</CardTitle></CardHeader><CardContent><div className="overflow-auto"><table className="min-w-full text-sm"><thead><tr className="border-b"><th className="text-left p-2">Tarih</th><th className="text-left p-2">Kanal</th><th className="text-left p-2">Misafir</th><th className="text-left p-2">Skor</th><th className="text-left p-2">Yorum</th></tr></thead><tbody>{reviews.slice(0,100).map((r:any)=><tr key={r.id} className="border-b"><td className="p-2">{new Date(r.review_date||r.reviewDate).toLocaleDateString('tr-TR')}</td><td className="p-2">{r.source}</td><td className="p-2">{r.guest_name||r.guestName||'-'}</td><td className="p-2 font-semibold">{r.score}</td><td className="p-2 max-w-xl">{r.comment||'-'}</td></tr>)}</tbody></table></div></CardContent></Card></div>
}
function Metric({icon,title,value}:{icon:any,title:string,value:any}){return <Card><CardContent className="p-4"><div className="text-xs text-muted-foreground">{title}</div><div className="flex items-center gap-2 mt-1"><span className="text-primary">{icon}</span><span className="text-2xl font-bold">{value}</span></div></CardContent></Card>}
